version: "3"
services:
  matchbox-test-app:
    build: .
    container_name: matchbox-test-app
    restart: on-failure
    ports:
      - "8080:8080"
    links:
      - matchbox-test-db
    volumes:
      - ./with-postgres:/config      
  matchbox-test-db:
    image: postgres:latest
    container_name: matchbox-test-db
    restart: always
    environment:
      POSTGRES_DB: 'matchbox'
      POSTGRES_USER: 'matchbox'
      POSTGRES_PASSWORD: 'matchbox'     
    volumes:
      - ./data:/var/lib/postgresql/data